name: nearby_service
description: Nearby Service Flutter Plugin is used to create connections in a P2P network. Supports sending text messages and files.
version: 0.0.4
homepage: https://github.com/ksenia312/nearby_service
repository: https://github.com/ksenia312/nearby_service

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.2
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1


flutter:
  plugin:
    platforms:
      android:
        package: com.xenikii.nearby_service
        pluginClass: NearbyServicePlugin
      ios:
        pluginClass: NearbyServicePlugin
